#!/bin/bash
./run-release -c config-files/evolve-entrance-positions-4-rows-with-energetics.cfg --num-bees 100 --num-trials-per-config 150 --num-generations=50 | tee out-sga-with-energetics-100-bees-150-reps-50-gens.txt
