#!/bin/bash
#
# Compares bee-movement flowmaps between two run_analysis.sh output
# directories (two different experimental conditions), producing axial
# angular-delta heatmaps and histograms for each flowmap cell size found.
#
# Run from the parent directory of the two condition directories:
#
#   run-cross-analysis.sh --title "TITLE" [options] DIR1 DIR2
#
# DIR1 and DIR2 must each be laid out as generated by run_analysis.sh (in
# particular, each needs a bee-flowmaps-agg/ subdirectory of merged
# per-cell-size flowmap CSVs, and a best-configs-indiv/ subdirectory).
#
# For each flowmap cell size present in both directories, gen_angdelta_data.py
# is run six times: with no thresholds and with the default (or supplied)
# strength/count thresholds, each at histogram bin sizes of 5, 10 and 15
# degrees. Each resulting angdelta heatmap is visualised with
# visualize_heatmap.py (fixed colour scale 0-pi/2) and each histogram with
# visualize_angdelta_histogram.py.
#
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: run-cross-analysis.sh --title "TITLE" [options] DIR1 DIR2

Required:
  --title "TITLE"              Title passed to visualize_heatmap.py and
                               visualize_angdelta_histogram.py for every plot
                               (suffixed with the thresholds used, for the
                               thresholded comparisons)
  DIR1, DIR2                   Two run_analysis.sh output directories to compare

Options:
  --flowmap-strength-th VAL    Strength threshold for the thresholded comparison
                               (default: 0.5)
  --flowmap-count-th VAL       Count threshold for the thresholded comparison
                               (default: 0.1)
  --output-dir DIR             Directory to write output into
                               (default: cross-analysis-<DIR1>-vs-<DIR2>)
  --tools-dir DIR              Directory containing the polybee analysis tools
                               (default: ~/polybee/tools)
  -h, --help                   Show this help
EOF
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
TITLE=""
FLOWMAP_STRENGTH_TH="0.5"
FLOWMAP_COUNT_TH="0.1"
OUTPUT_DIR=""
TOOLS_DIR="$HOME/polybee/tools"
POSITIONAL=()

while [ $# -gt 0 ]; do
    case "$1" in
        --title) TITLE="$2"; shift 2 ;;
        --flowmap-strength-th) FLOWMAP_STRENGTH_TH="$2"; shift 2 ;;
        --flowmap-count-th) FLOWMAP_COUNT_TH="$2"; shift 2 ;;
        --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
        --tools-dir) TOOLS_DIR="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        --) shift; while [ $# -gt 0 ]; do POSITIONAL+=("$1"); shift; done ;;
        -*) echo "Error: unknown argument: $1" >&2; usage >&2; exit 1 ;;
        *) POSITIONAL+=("$1"); shift ;;
    esac
done

if [ -z "$TITLE" ]; then
    echo "Error: --title is required." >&2
    usage >&2
    exit 1
fi

if [ ${#POSITIONAL[@]} -ne 2 ]; then
    echo "Error: expected exactly two directory arguments, got ${#POSITIONAL[@]}." >&2
    usage >&2
    exit 1
fi
DIR1="${POSITIONAL[0]}"
DIR2="${POSITIONAL[1]}"

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="cross-analysis-$(basename "$DIR1")-vs-$(basename "$DIR2")"
fi

# ---------------------------------------------------------------------------
# Verify input directories are laid out as expected
# ---------------------------------------------------------------------------
for D in "$DIR1" "$DIR2"; do
    if [ ! -d "$D" ]; then
        echo "Error: directory not found: $D" >&2
        exit 1
    fi
    if [ ! -d "$D/bee-flowmaps-agg" ]; then
        echo "Error: '$D/bee-flowmaps-agg' not found. Expected '$D' to be a run_analysis.sh output directory." >&2
        exit 1
    fi
    if [ ! -d "$D/best-configs-indiv" ]; then
        echo "Error: '$D/best-configs-indiv' not found. Expected '$D' to be a run_analysis.sh output directory." >&2
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Detect flowmap cell sizes present in DIR1's bee-flowmaps-agg
# ---------------------------------------------------------------------------
shopt -s nullglob
dir1_flowmap_files=("$DIR1"/bee-flowmaps-agg/bee-flowmap-size-*-intra-condition-merged-*.csv)
shopt -u nullglob
if [ ${#dir1_flowmap_files[@]} -eq 0 ]; then
    echo "Error: no bee-flowmap-size-*-intra-condition-merged-*.csv files found in '$DIR1/bee-flowmaps-agg'." >&2
    exit 1
fi

CELL_SIZES=()
for f in "${dir1_flowmap_files[@]}"; do
    sz=$(basename "$f" | sed -E 's/^bee-flowmap-size-([0-9]+)-intra-condition-merged-.*\.csv$/\1/')
    case " ${CELL_SIZES[*]:-} " in
        *" $sz "*) ;;
        *) CELL_SIZES+=("$sz") ;;
    esac
done
IFS=$'\n' CELL_SIZES=($(sort -n <<< "${CELL_SIZES[*]}")); unset IFS

find_flowmap() {
    local dir="$1" size="$2"
    shopt -s nullglob
    local matches=("$dir"/bee-flowmaps-agg/bee-flowmap-size-"$size"-intra-condition-merged-*.csv)
    shopt -u nullglob
    if [ ${#matches[@]} -ne 1 ]; then
        echo "Error: expected exactly one merged flowmap CSV for cell size $size in '$dir/bee-flowmaps-agg', found ${#matches[@]}." >&2
        exit 1
    fi
    echo "${matches[0]}"
}

# ---------------------------------------------------------------------------
# Config file (assumes both conditions share the same basic environment)
# ---------------------------------------------------------------------------
shopt -s nullglob
cfg_matches=("$DIR1"/best-configs-indiv/best-*_1.cfg)
shopt -u nullglob
if [ ${#cfg_matches[@]} -eq 0 ]; then
    echo "Error: no best-*_1.cfg found in '$DIR1/best-configs-indiv'." >&2
    exit 1
fi
CONFIG_FILE="${cfg_matches[0]}"

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
if [ ! -d "$OUTPUT_DIR" ]; then
    echo "Creating directory: $OUTPUT_DIR"
    mkdir "$OUTPUT_DIR"
fi

# ---------------------------------------------------------------------------
# Generate and visualise angular-delta heatmaps/histograms
# ---------------------------------------------------------------------------
BIN_SIZES=(5 10 15)
THRESH_STRENGTH_VALUES=(0.0 "$FLOWMAP_STRENGTH_TH")
THRESH_COUNT_VALUES=(0.0 "$FLOWMAP_COUNT_TH")
THRESH_LABELS=(nothresh thresh)

for SZ in "${CELL_SIZES[@]}"; do
    echo "== Cell size $SZ =="
    FLOWMAP1=$(find_flowmap "$DIR1" "$SZ")
    FLOWMAP2=$(find_flowmap "$DIR2" "$SZ")

    for i in 0 1; do
        ST="${THRESH_STRENGTH_VALUES[$i]}"
        CT="${THRESH_COUNT_VALUES[$i]}"

        if [ "${THRESH_LABELS[$i]}" = "nothresh" ]; then
            PLOT_TITLE="$TITLE"
        else
            PLOT_TITLE="${TITLE} (thresholds: count=${CT}, strength=${ST})"
        fi

        for BIN in "${BIN_SIZES[@]}"; do
            BASENAME="${OUTPUT_DIR}/size-${SZ}-bin${BIN}-${THRESH_LABELS[$i]}"

            "${TOOLS_DIR}/gen_angdelta_data.py" "$FLOWMAP1" "$FLOWMAP2" \
                --strength-th "$ST" --count-th "$CT" --bin-size "$BIN" --basename "$BASENAME"

            shopt -s nullglob
            heatmap_csv=("${BASENAME}-angdelta-heatmap-"*.csv)
            histogram_csv=("${BASENAME}-angdelta-histogram-"*.csv)
            shopt -u nullglob
            if [ ${#heatmap_csv[@]} -ne 1 ] || [ ${#histogram_csv[@]} -ne 1 ]; then
                echo "Error: expected exactly one heatmap and one histogram CSV for basename '$BASENAME'." >&2
                exit 1
            fi

            "${TOOLS_DIR}/visualize_heatmap.py" --config "$CONFIG_FILE" --color-scale-max 1.5708 \
                --title "$PLOT_TITLE" --save-only "${heatmap_csv[0]}"

            "${TOOLS_DIR}/visualize_angdelta_histogram.py" --title "$PLOT_TITLE" --save-only "${histogram_csv[0]}"
        done
    done
done

echo "Done."
